# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_registration_app.Quote')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_registration_app.Users')),
            ],
        ),
    ]
